Update README.md
mrblamber/finance-manager-bot pull request #4
Opened 2018-05-30 09:47 UTC by tarnenaky

2018-05-30 09:48 UTC, mrblamber commented on README.md
> +# looks-like-gauno-bot
It's wrong statement.

2018-05-30 09:50 UTC, aliaksanderkazlou requested changes
Need fixes

2018-05-30 09:52 UTC, tarnenaky commented
I think now is better

2018-05-30 09:55 UTC, aliaksanderkazlou requested changes
sosi

2018-05-30 09:55 UTC, mrblamber commented on README.md
> +# looks-like-pedar-gauno-bot
-

2018-05-30 14:01 UTC, tarnenaky commented
Accept this request, pedar

2018-05-31 06:07 UTC, mrblamber commented
-

2018-05-31 06:09 UTC, closed without merging